select_dbs_to_drop = """SELECT DISTINCT ETL.DATABASE_NAME, ETL.END_DATE
FROM FRAMEWORK.LOOKUP.ETL_ENGAGEMENT_INFORMATION ETL
JOIN SNOWFLAKE.ACCOUNT_USAGE.DATABASES DBS USING (DATABASE_NAME)
WHERE ETL.END_DATE <= DATEADD('DAY', -7, CURRENT_DATE())
    AND DBS.DELETED IS NULL
ORDER BY END_DATE DESC;"""

drop_stmnt = """USE ROLE SYSADMIN;
DROP DATABASE {{params.db_name}};"""