name: "Check PR content does not contain DEV"
on: [pull_request]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR
      uses: JJ/github-pr-contains-action@releases/v11
      with:
        github-token: ${{github.token}}
        diffDoesNotContain: "DEV"
